钓鱼加了几个战利品，调大了延时时间（60）
CrashVibe/U1bot pull request #108
Opened 2024-04-06 12:42 UTC by ajjdxns

一个PR

2024-04-06 12:45 UTC, haitang000 requested changes
请不要修改冷却时间

2024-04-07 01:51 UTC, ajjdxns commented on .env
> +SESSION_EXPIRE_TIMEOUT=40
呃

2024-04-07 01:51 UTC, ajjdxns commented on .env
> +SESSION_EXPIRE_TIMEOUT=40
我去改下

2024-04-07 10:29 UTC, haitang000 approved these changes

2024-04-08 13:42 UTC, ajjdxns commented
还有没有人嘞

2024-04-12 09:23 UTC, wling-art submitted a review, later dismissed
很好，没有什么问题，我知道原本要改很多东西，最后却只增加了个空气（

2024-04-12 09:34 UTC, wling-art commented
@ajjdxns 你的貌似冲突了

2024-04-12 14:16 UTC, ajjdxns commented
> @ajjdxns 你的貌似冲突了

冲突在哪里？

2024-04-12 14:20 UTC, wling-art commented
> > @ajjdxns 你的貌似冲突了
> 
> 冲突在哪里？

请使用git看，github无法显示冲突，过于复杂

2024-04-16 17:17 UTC, merged

2024-05-15 06:54 UTC, ajjdxns commented
发生什么了